feat: update lazy ape logo
yearn/yearn-finance pull request #388
Opened 2021-07-01 17:28 UTC by patcito

2021-07-01 17:28 UTC, yearn-integrations commented
## Important changes detected  (payment related code)
- Found address [0xd533a949740bb3306d119cc777fa900ba034cd52](https://etherscan.io/address/0xd533a949740bb3306d119cc777fa900ba034cd52) in files app/components/Vault/index.js. This address is from token `CRV`  
- Found address [0xc5bddf9843308380375a611c18b50fb9341f502a](https://etherscan.io/address/0xc5bddf9843308380375a611c18b50fb9341f502a) in files app/components/Vault/index.js. This address is from vault `yveCRV`

2021-07-01 19:28 UTC, xgambitox approved these changes

2021-07-01 19:48 UTC, yearn-integrations commented
## Important changes detected  (payment related code)
- Found address [0xd533a949740bb3306d119cc777fa900ba034cd52](https://etherscan.io/address/0xd533a949740bb3306d119cc777fa900ba034cd52) in files app/components/Vault/index.js. This address is from token `CRV`  
- Found address [0xc5bddf9843308380375a611c18b50fb9341f502a](https://etherscan.io/address/0xc5bddf9843308380375a611c18b50fb9341f502a) in files app/components/Vault/index.js. This address is from vault `yveCRV`  
- Found address [0x2a38B9B0201Ca39B17B460eD2f11e4929559071E](https://etherscan.io/address/0x2a38B9B0201Ca39B17B460eD2f11e4929559071E) in files app/containers/Vaults/constants.js. This address is from vault `yvCurve-GUSD`  
- Found address [0x4B5BfD52124784745c1071dcB244C6688d2533d3](https://etherscan.io/address/0x4B5BfD52124784745c1071dcB244C6688d2533d3) in files app/containers/Vaults/constants.js. This address is from vault `yUSD`  
- Found address [0x8ee57c05741aA9DB947A744E713C15d4d19D8822](https://etherscan.io/address/0x8ee57c05741aA9DB947A744E713C15d4d19D8822) in files app/containers/Vaults/constants.js. This address is from vault `yvCurve-yBUSD`  
- Found address [0xD6Ea40597Be05c201845c0bFd2e96A60bACde267](https://etherscan.io/address/0xD6Ea40597Be05c201845c0bFd2e96A60bACde267) in files app/containers/Vaults/constants.js. This address is from vault `yvCurve-Compound`  
- Found address [0x84E13785B5a27879921D6F685f041421C7F482dA](https://etherscan.io/address/0x84E13785B5a27879921D6F685f041421C7F482dA) in files app/containers/Vaults/constants.js. This address is from vault `yvCurve-3pool`  
- Found address [0x6Ede7F19df5df6EF23bD5B9CeDb651580Bdf56Ca](https://etherscan.io/address/0x6Ede7F19df5df6EF23bD5B9CeDb651580Bdf56Ca) in files app/containers/Vaults/constants.js. This address is from vault `yvCurve-BUSD`  
- Found address [0xC4dAf3b5e2A9e93861c3FBDd25f1e943B8D87417](https://etherscan.io/address/0xC4dAf3b5e2A9e93861c3FBDd25f1e943B8D87417) in files app/containers/Vaults/constants.js. This address is from vault `yvCurve-USDP`  
- Found address [0x5fA5B62c8AF877CB37031e0a3B2f34A78e3C56A6](https://etherscan.io/address/0x5fA5B62c8AF877CB37031e0a3B2f34A78e3C56A6) in files app/containers/Vaults/constants.js. This address is from vault `yvCurve-LUSD`  
- Found address [0x3B96d491f067912D18563d56858Ba7d6EC67a6fa](https://etherscan.io/address/0x3B96d491f067912D18563d56858Ba7d6EC67a6fa) in files app/containers/Vaults/constants.js. This address is from vault `yvCurve-USDN`

2021-07-01 20:04 UTC, xgambitox requested changes

2021-07-01 20:04 UTC, xgambitox commented on app/containers/Vaults/constants.js
> +  '0x3B96d491f067912D18563d56858Ba7d6EC67a6fa ',
There is a space at the end of the string, so button does not displays for crvUSDN

2021-07-01 20:06 UTC, yearn-integrations commented
## Important changes detected  (payment related code)
- Found address [0xd533a949740bb3306d119cc777fa900ba034cd52](https://etherscan.io/address/0xd533a949740bb3306d119cc777fa900ba034cd52) in files app/components/Vault/index.js. This address is from token `CRV`  
- Found address [0xc5bddf9843308380375a611c18b50fb9341f502a](https://etherscan.io/address/0xc5bddf9843308380375a611c18b50fb9341f502a) in files app/components/Vault/index.js. This address is from vault `yveCRV`  
- Found address [0x2a38B9B0201Ca39B17B460eD2f11e4929559071E](https://etherscan.io/address/0x2a38B9B0201Ca39B17B460eD2f11e4929559071E) in files app/containers/Vaults/constants.js. This address is from vault `yvCurve-GUSD`  
- Found address [0x4B5BfD52124784745c1071dcB244C6688d2533d3](https://etherscan.io/address/0x4B5BfD52124784745c1071dcB244C6688d2533d3) in files app/containers/Vaults/constants.js. This address is from vault `yUSD`  
- Found address [0x8ee57c05741aA9DB947A744E713C15d4d19D8822](https://etherscan.io/address/0x8ee57c05741aA9DB947A744E713C15d4d19D8822) in files app/containers/Vaults/constants.js. This address is from vault `yvCurve-yBUSD`  
- Found address [0xD6Ea40597Be05c201845c0bFd2e96A60bACde267](https://etherscan.io/address/0xD6Ea40597Be05c201845c0bFd2e96A60bACde267) in files app/containers/Vaults/constants.js. This address is from vault `yvCurve-Compound`  
- Found address [0x84E13785B5a27879921D6F685f041421C7F482dA](https://etherscan.io/address/0x84E13785B5a27879921D6F685f041421C7F482dA) in files app/containers/Vaults/constants.js. This address is from vault `yvCurve-3pool`  
- Found address [0x6Ede7F19df5df6EF23bD5B9CeDb651580Bdf56Ca](https://etherscan.io/address/0x6Ede7F19df5df6EF23bD5B9CeDb651580Bdf56Ca) in files app/containers/Vaults/constants.js. This address is from vault `yvCurve-BUSD`  
- Found address [0xC4dAf3b5e2A9e93861c3FBDd25f1e943B8D87417](https://etherscan.io/address/0xC4dAf3b5e2A9e93861c3FBDd25f1e943B8D87417) in files app/containers/Vaults/constants.js. This address is from vault `yvCurve-USDP`  
- Found address [0x5fA5B62c8AF877CB37031e0a3B2f34A78e3C56A6](https://etherscan.io/address/0x5fA5B62c8AF877CB37031e0a3B2f34A78e3C56A6) in files app/containers/Vaults/constants.js. This address is from vault `yvCurve-LUSD`  
- Found address [0x3B96d491f067912D18563d56858Ba7d6EC67a6fa](https://etherscan.io/address/0x3B96d491f067912D18563d56858Ba7d6EC67a6fa) in files app/containers/Vaults/constants.js. This address is from vault `yvCurve-USDN`

2021-07-01 20:06 UTC, patcito commented
pushed a fix

On Fri, Jul 2, 2021 at 12:04 AM xgambitox ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In app/containers/Vaults/constants.js
> <https://github.com/yearn/yearn-finance/pull/388#discussion_r662559270>:
>
> > @@ -56,11 +56,10 @@ export const AMPLIFY_VAULTS_ADDRESSES = [
>  export const ZAP_V2_3CRV = '0x579422a1c774470ca623329c69f27cc3beb935a1';
>
>  export const LAZY_APE_ADDRESSES = [
> -  '0x2a38B9B0201Ca39B17B460eD2f11e4929559071E',
> -  '0x4B5BfD52124784745c1071dcB244C6688d2533d3',
> -  '0x8ee57c05741aA9DB947A744E713C15d4d19D8822',
> -  '0xD6Ea40597Be05c201845c0bFd2e96A60bACde267',
> -  '0x84E13785B5a27879921D6F685f041421C7F482dA',
> +  '0x6Ede7F19df5df6EF23bD5B9CeDb651580Bdf56Ca',
> +  '0xC4dAf3b5e2A9e93861c3FBDd25f1e943B8D87417',
> +  '0x5fA5B62c8AF877CB37031e0a3B2f34A78e3C56A6',
> +  '0x3B96d491f067912D18563d56858Ba7d6EC67a6fa ',
>
> There is a space at the end of the string, so button does not displays for
> crvUSDN
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/yearn/yearn-finance/pull/388#pullrequestreview-697610858>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAGOQ3FZUWFMNTUIKY3QLDTVTC6LANCNFSM47VE4QBQ>
> .
>

2021-07-01 20:13 UTC, xgambitox approved these changes

2021-07-03 15:08 UTC, dudesahn approved these changes

2021-07-03 15:08 UTC, merged